---
title: "VIIRS Explorer"
format: html
editor: visual
---

# TASK:

retrieve and compare [VIIRS](https://lpdaac.usgs.gov/data/get-started-data/collection-overview/missions/s-npp-nasa-viirs-overview/) v2 surface reflectance data pairs files from both [opendap](https://opendap.cr.usgs.gov/opendap/hyrax/MCD12Q2.061/h16v07.ncml.html) (test data, netCDF, .nc4) and [EarthDataSearch](https://search.earthdata.nasa.gov/search) (reference data, hdf5, .h5). Compare numerical data values *and* the metadata between files to make sure they are functionally equivalent.

 use **tile list** from each quadrant of Earth; can see tiles [here](https://modis-land.gsfc.nasa.gov/MODLAND_grid.html). These specific tiles have been selected to capture variation in land and water coverage.


run through this script

\-\-\-\-\-- download /// run the comparison

\-\-\-\-\--reduce to 4 instead of 8

+-------------+----------+----------+
|             | Northern | Southern |
+=============+==========+==========+
| **Eastern** | h10v03   | h10v09   |
|             |          |          |
|             | h11v05   | h13v12   |
+-------------+----------+----------+
| **Western** | h18v03   | h21v09   |
|             |          |          |
|             | h24v06   | h30v10   |
+-------------+----------+----------+

## Basic Product Information

Use the list below (n=10) and **consider** Attributes ( offset, scale factor, units, valid range) and types (signed/unsigned integer) associated with the data

<div>

+-------------+-------------+----------------------------+---------------------+
| Data        | Collection  | Spatial Resolution **(m)** | Temporal Resolution |
+=============+=============+============================+=====================+
| VNP09A1     | S.N.VIIRS   | 1000                       | 8-day               |
+-------------+-------------+----------------------------+---------------------+
| VNP09GA     | S.N.VIIRS   | 1000                       | daily               |
+-------------+-------------+----------------------------+---------------------+
| VNP09GA     | S.N.VIIRS   | 500                        | daily               |
+-------------+-------------+----------------------------+---------------------+
| VNP09H1     | S.N.VIIRS   | 500                        | 8-day               |
+-------------+-------------+----------------------------+---------------------+
| VJ09A1      | NOAA-20     | 1000                       | 8-day               |
+-------------+-------------+----------------------------+---------------------+
| VJ109GA     | NOAA-20     | 1000                       | daily               |
+-------------+-------------+----------------------------+---------------------+
| VJ109GA     | NOAA-20     | 500                        | daily               |
+-------------+-------------+----------------------------+---------------------+
| VJ109H1     | NOAA-20     | 500                        | daily               |
+-------------+-------------+----------------------------+---------------------+

</div>


## Part 2: Data Values

Use the list below (n=34) and **consider** Data numerical values; use difference test.

+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| Data                                                         | Spatial Resolution **(m)** | Temporal Resolution | Data Type       | Layer Name              |
+==============================================================+============================+=====================+=================+=========================+
| [**VNP09A1**](https://lpdaac.usgs.gov/products/vnp09a1v002/) | 1000                       | 8-day               | 16-bit unsigned | SurfReflect_Day_Of_Year |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | 8-day               | 16-bit signed   | SurfReflect_M1_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | 8-day               | 32-bit unsigned | SurfReflect_QC          |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| [**VNP09GA**](https://lpdaac.usgs.gov/products/vnp09gav002/) | 1000                       | daily               | 8-bit unsigned  | land_water_mask_c       |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 8-bit signed    | obscov_1km_c            |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 16-bit signed   | SolarZenith_c           |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 32-bit signed   | nadd_obs_row_1km        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 16-bit signed   | SurfReflect_M4_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 8-bit signed    | obscov_500m_c           |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 32-bit signed   | nadd_obs_row_500m       |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 16-bit signed   | SurfReflect_I3_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| [**VNP09H1**](https://lpdaac.usgs.gov/products/vnp09h1v002/) | 500                        | 8-day               | 16-bit unsigned | SurfReflect_I3          |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | 8-day               | 16-bit signed   | SurfReflect_QC_500m     |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| [**VJ09A1**](https://lpdaac.usgs.gov/products/vj109a1v002/)  | 1000                       | 8-day               | 16-bit unsigned | SurfReflect_Day_Of_Year |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | 8-day               | 16-bit signed   | SurfReflect_M1_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | 8-day               | 32-bit unsigned | SurfReflect_QC          |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| [**VJ109GA**](https://lpdaac.usgs.gov/products/vj109gav002/) | 1000                       | daily               | 8-bit unsigned  | land_water_maks_c       |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 8-bit signed    | obscov_1km_c            |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 16-bit signed   | SurfReflect_M4_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 1000                       | daily               | 32-bit signed   | nadd_obs_row_1km        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 16-bit signed   | SurfReflect_I3_1        |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 8-bit signed    | obscov_500m_c           |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 32-bit signed   | nadd_obs_row_500m       |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
| [**VJ109H1**](https://lpdaac.usgs.gov/products/vj109h1v002/) | 500                        | daily               | 16-bit unsigned | SurfReflect_I3          |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+
|                                                              | 500                        | daily               | 16-bit signed   | SurfReflect_QC_500m     |
+--------------------------------------------------------------+----------------------------+---------------------+-----------------+-------------------------+

